/* *************************************************************************************************************************************** *\
 * COPYRIGHT © 2006 - 2022 WANG YUCAI. ALL RIGHTS RESERVED.                                                                                *
 * LICENSED UNDER THE MIT LICENSE. SEE LICENSE FILE IN THE PROJECT ROOT FOR FULL LICENSE INFORMATION.                                      *
\* *************************************************************************************************************************************** */

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "Ex0200:Member is documented as throwing exception not documented on member in base or interface type", Justification = "<挂起>", Scope = "member", Target = "~M:Niacomsoft.Eips.Reflection.AssemblyAttributeHelper.GetCustomAttribute``1(System.Reflection.Assembly,System.Boolean)~``0")]
[assembly: SuppressMessage("Design", "Ex0200:Member is documented as throwing exception not documented on member in base or interface type", Justification = "<挂起>", Scope = "member", Target = "~M:Niacomsoft.Eips.Reflection.MemberAttributeHelper.GetCustomAttribute``1(System.Reflection.MemberInfo,System.Boolean)~``0")]
[assembly: SuppressMessage("Design", "Ex0200:Member is documented as throwing exception not documented on member in base or interface type", Justification = "<挂起>", Scope = "member", Target = "~M:Niacomsoft.Eips.Reflection.MemberAttributeHelper.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)~System.Collections.Generic.IEnumerable{System.Attribute}")]
[assembly: SuppressMessage("Design", "Ex0200:Member is documented as throwing exception not documented on member in base or interface type", Justification = "<挂起>", Scope = "member", Target = "~M:Niacomsoft.Eips.Reflection.MemberAttributeHelper.GetCustomAttributes``1(System.Reflection.MemberInfo,System.Boolean)~System.Collections.Generic.IEnumerable{``0}")]
[assembly: SuppressMessage("Design", "Ex0200:Member is documented as throwing exception not documented on member in base or interface type", Justification = "<挂起>", Scope = "member", Target = "~M:Niacomsoft.Eips.EnvironmentVariableAccessor.GetEnvironmentVariable(System.String)~Niacomsoft.Eips.IEnvironmentVariable")]
[assembly: SuppressMessage("Design", "Ex0100:Member may throw undocumented exception", Justification = "<挂起>", Scope = "member", Target = "~M:Niacomsoft.Eips.EnvironmentVariableAccessor.GetEnvironmentVariable(System.String)~Niacomsoft.Eips.IEnvironmentVariable")]
[assembly: SuppressMessage("Design", "Ex0200:Member is documented as throwing exception not documented on member in base or interface type", Justification = "<挂起>", Scope = "member", Target = "~M:Niacomsoft.Eips.Security.Cryptography.MD5AlgorithmsProvider.ComputeHash(System.Byte[])~System.Byte[]")]
[assembly: SuppressMessage("Design", "Ex0200:Member is documented as throwing exception not documented on member in base or interface type", Justification = "<挂起>", Scope = "member", Target = "~M:Niacomsoft.Eips.Security.Cryptography.MD5AlgorithmsProvider.ComputeHash(System.Byte[],System.IO.Stream)")]
[assembly: SuppressMessage("Design", "Ex0200:Member is documented as throwing exception not documented on member in base or interface type", Justification = "<挂起>", Scope = "member", Target = "~M:Niacomsoft.Eips.Security.Cryptography.SHA1AlgorithmsProvider.ComputeHash(System.Byte[])~System.Byte[]")]
[assembly: SuppressMessage("Design", "Ex0200:Member is documented as throwing exception not documented on member in base or interface type", Justification = "<挂起>", Scope = "member", Target = "~M:Niacomsoft.Eips.Security.Cryptography.SHA1AlgorithmsProvider.ComputeHash(System.Byte[],System.IO.Stream)")]
[assembly: SuppressMessage("Design", "Ex0200:Member is documented as throwing exception not documented on member in base or interface type", Justification = "<挂起>", Scope = "member", Target = "~M:Niacomsoft.Eips.Security.Cryptography.SHA256AlgorithmsProvider.ComputeHash(System.Byte[])~System.Byte[]")]
[assembly: SuppressMessage("Design", "Ex0200:Member is documented as throwing exception not documented on member in base or interface type", Justification = "<挂起>", Scope = "member", Target = "~M:Niacomsoft.Eips.Security.Cryptography.SHA256AlgorithmsProvider.ComputeHash(System.Byte[],System.IO.Stream)")]
[assembly: SuppressMessage("Design", "Ex0200:Member is documented as throwing exception not documented on member in base or interface type", Justification = "<挂起>", Scope = "member", Target = "~M:Niacomsoft.Eips.Security.Cryptography.SHA384AlgorithmsProvider.ComputeHash(System.Byte[])~System.Byte[]")]
[assembly: SuppressMessage("Design", "Ex0200:Member is documented as throwing exception not documented on member in base or interface type", Justification = "<挂起>", Scope = "member", Target = "~M:Niacomsoft.Eips.Security.Cryptography.SHA384AlgorithmsProvider.ComputeHash(System.Byte[],System.IO.Stream)")]
[assembly: SuppressMessage("Design", "Ex0100:Member may throw undocumented exception", Justification = "<挂起>", Scope = "member", Target = "~M:Niacomsoft.Eips.Security.RandomPasswordGenerator.#ctor")]
[assembly: SuppressMessage("Design", "Ex0200:Member is documented as throwing exception not documented on member in base or interface type", Justification = "<挂起>", Scope = "member", Target = "~M:Niacomsoft.Eips.Runtime.Serializations.BinarySerializer.Deserialize``1(System.IO.Stream)~``0")]
[assembly: SuppressMessage("Design", "Ex0100:Member may throw undocumented exception", Justification = "<挂起>", Scope = "member", Target = "~M:Niacomsoft.Eips.Runtime.Serializations.BinarySerializer.SerializableAttributeNotFound(System.Type)")]
[assembly: SuppressMessage("Design", "Ex0200:Member is documented as throwing exception not documented on member in base or interface type", Justification = "<挂起>", Scope = "member", Target = "~M:Niacomsoft.Eips.Runtime.Serializations.BinarySerializer.Serialize``1(``0,System.IO.Stream)")]
