//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niacomsoft.Eips.Globalization.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Niacomsoft.Eips.Globalization.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 中止 的本地化字符串。
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接受 的本地化字符串。
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 “{0}” 不能为 null 或者空白。 的本地化字符串。
        /// </summary>
        internal static string ArgumentException_empty_or_whitespace {
            get {
                return ResourceManager.GetString("ArgumentException_empty_or_whitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 询问 的本地化字符串。
        /// </summary>
        internal static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        internal static string Check_Out {
            get {
                return ResourceManager.GetString("Check_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成了 的本地化字符串。
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续 的本地化字符串。
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建 的本地化字符串。
        /// </summary>
        internal static string Create_New {
            get {
                return ResourceManager.GetString("Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 危险的 的本地化字符串。
        /// </summary>
        internal static string Dangerous {
            get {
                return ResourceManager.GetString("Dangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy年MM月dd日 的本地化字符串。
        /// </summary>
        internal static string DateTime_formatter {
            get {
                return ResourceManager.GetString("DateTime_formatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试 的本地化字符串。
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 彻底删除 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完毕 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试创建 “{0}” 类型对象实例时，引发了异常。 的本地化字符串。
        /// </summary>
        internal static string DynamicCreateObjectInstanceException_default_message {
            get {
                return ResourceManager.GetString("DynamicCreateObjectInstanceException_default_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “Enterprise InPrivate SaaS” 引发了一个未处理的异常。 的本地化字符串。
        /// </summary>
        internal static string Exception_default_message {
            get {
                return ResourceManager.GetString("Exception_default_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 致命的 的本地化字符串。
        /// </summary>
        internal static string Fatal {
            get {
                return ResourceManager.GetString("Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        internal static string Get_Started {
            get {
                return ResourceManager.GetString("Get_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放弃 的本地化字符串。
        /// </summary>
        internal static string Give_Up {
            get {
                return ResourceManager.GetString("Give_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Mistake {
            get {
                return ResourceManager.GetString("Mistake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不了，谢谢 的本地化字符串。
        /// </summary>
        internal static string No_Thanks {
            get {
                return ResourceManager.GetString("No_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 好的 的本地化字符串。
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拒绝 的本地化字符串。
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为 的本地化字符串。
        /// </summary>
        internal static string Save_As {
            get {
                return ResourceManager.GetString("Save_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string Sign_In {
            get {
                return ResourceManager.GetString("Sign_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        internal static string Sign_Out {
            get {
                return ResourceManager.GetString("Sign_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        internal static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当然 的本地化字符串。
        /// </summary>
        internal static string Sure {
            get {
                return ResourceManager.GetString("Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 追踪 的本地化字符串。
        /// </summary>
        internal static string Trace {
            get {
                return ResourceManager.GetString("Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是的 的本地化字符串。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
